title: Amre PixelWitch
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  An Irish woman living at the intersection of code and creativity.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amre-pixelwitch.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: your-twitter-username
github_username:  Amrree

# Build settings
theme: jekyll-theme-midnight
gem 'jekyll-feed'
gem 'jekyll-seo-tag'

# Theme settings
show_excerpts: true # set to false to remove excerpts on the homepage
minimal_mistakes_skin: "midnight" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Collections
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
